Fixed squared FAB on Android 4.4 (small screens)
markormesher/android-fab pull request #7
Opened 2017-02-13 16:35 UTC by amatsegor

Also, added fabBackgroundColor

2017-02-13 16:57 UTC, amatsegor commented
What was the problem, actually
https://pp.vk.me/c837221/v837221724/2581a/p4Fla-LLcIg.jpg

2017-02-14 16:26 UTC, markormesher commented
For the time being, could you move work for the background colour attribute to a new PR please? It's going to introduce a few breaking changes for existing users, so I'd rather keep it separate for now.

Also a few comments on the work to fix the squared FAB:
- There are still a lot of changes that are only line breaks or indentation, which make the diff harder to read (and break the style of the project). If you take a look at the diff and at existing files, you'll see the conventions that have been set in the project for indentation, XML formatting, etc.-
- Make sure you update documentation and comments when you update the code they apply to. For example, where you've changed `CardView` for `ImageButton`, the documentation still says `CardView`.
- Be aware of the implications of switching the `CardView` for an `ImageView` - make sure things like elevation and the background ripple effect stay consistent.

I apologise if any of this feel "picky" - I do appreciate your contribution! Feel free to make updates and comments in this PR; no need to delete and make a new one :)

2017-02-16 12:13 UTC, amatsegor commented
Ok, will move it now

Sorry for some unchanged docs and code, I'll recheck and fix it now.

After switching from CardView, I've checked all states either on >A5.0 and <=A4.4, so it's got to work okay.

No problem at all, I agree with your feedback)

2017-02-16 13:56 UTC, amatsegor commented
@markormesher done
Fixed button states on pre-Lollipop

2017-02-22 19:58 UTC, markormesher requested changes
I've made some comments on areas that need to be adjusted to keep consistency with the rest of the project - mostly whitespace. You can check the "Files Changed" tab on GH when you make changes - it should only be highlighting your explicit code changes. Thanks again for your contributions so far :smiley:

2017-02-22 19:58 UTC, markormesher commented on app/build.gradle
> +//			signingConfig signingConfigs.main
Why was this commented out?

2017-02-22 19:58 UTC, markormesher commented on app/src/main/res/layout/fab_activity.xml
> +        android:layout_height="match_parent"/>
Tabs/line breaks.

2017-02-22 19:58 UTC, markormesher commented on app/src/main/res/layout/fab_activity.xml
> +	xmlns:app="http://schemas.android.com/apk/res-auto"
Tabs/line breaks.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/java/uk/co/markormesher/android_fab/FloatingActionButton.java
> +
This needs to report a failure if the change was aborted here. The `background` variable is also unnecessary - it's accessed just once, so you can put `fab.get...` in the `if` condition.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/java/uk/co/markormesher/android_fab/FloatingActionButton.java
> +            setViewBackgroundTintColour(view.findViewById(R.id.card), menuAdapter.getBackgroundColour(i));
Tabs/line breaks.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/res/drawable-v21/fab_cover_circle.xml
> +</ripple>
Tabs/line breaks.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/res/drawable-v21/fab_cover_circle.xml
> +</ripple>
Please use 6- or 8-digit colour codes to keep consistency with the rest of the project.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/res/drawable/fab_cover_circle.xml
> +</selector>
Please use 6- or 8-digit colour codes to keep consistency with the rest of the project.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/res/drawable/fab_cover_circle.xml
> +</selector>
Tabs/line breaks.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/res/drawable/fab_round_shape.xml
> +</shape>
Please use 6- or 8-digit colour codes to keep consistency with the rest of the project.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/res/drawable/fab_round_shape.xml
> +</shape>
Tabs/line breaks.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/res/layout/floating_action_button.xml
>  </RelativeLayout>
Tabs/line breaks throughout.

2017-02-22 19:58 UTC, markormesher commented on fab/src/main/res/layout/speed_dial_icon.xml
>  </LinearLayout>
Tabs/line breaks throughout.

2017-05-25 15:20 UTC, markormesher commented
This seems to have gone cold and has been fixed anyway in v1.3.0. I'll close this, but thank you for your efforts!

2017-05-25 15:20 UTC, closed without merging